version: '3'
services: 
  covid19:
    restart: always
    build: .
    ports:
      - "8282:8282"
  prometheus:
    image: prom/prometheus:latest
    restart: always
    depends_on:
      - covid19
    ports:
      - "9090:9090"
    volumes:
      - ./config/prometheus.yml:/etc/prometheus/prometheus.yml
      - ./data/prometheus:/prometheus
  grafana:
    image: grafana/grafana:latest
    restart: always
    environment:
      GF_SECURITY_ADMIN_PASSWORD: "admin"
      GF_USERS_ALLOW_SIGN_UP: "false"
      GF_AUTH_ANONYMOUS_ENABLED: "true"
      GF_AUTH_ANONYMOUS_ORG_NAME: "Main Org."
      GF_AUTH_ANONYMOUS_ORG_ROLE: "Viewer"
    depends_on: 
      - prometheus
    ports:
      - "3000:3000"
    volumes:
      - ./config/datasource:/etc/grafana/provisioning/datasources
      - ./config/dashboard:/etc/grafana/provisioning/dashboards
      - ./data/grafana:/var/lib/grafana