{
 "title": "Covid-19",
 "time": { "from": "now-24h", "to": "now" },
 "refresh": "5s",
 "panels": [
  {
   "title": "Cov19 Tests",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 0, "y": 0 },
   "targets": [
    { "expr": "cov19_tests " }
   ]
  },
  {
   "title": "Cov19 Confirmed",
   "type": "stat",
   "gridPos": { "h": 5, "w": 6, "x": 6, "y": 0 },
   "targets": [
    { "expr": "cov19_confirmed " }
   ]
  },
  {
   "title": "Fälle in Österreich",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 0 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_detail{country=\"Austria\"}) without (instance,job)",
     "legendFormat": "{{province}}"
    }
   ]
  },
  {
   "title": "Confirmed cases Austria",
   "type": "graph",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 5 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_confirmed) without (instance,job)",
     "legendFormat": "Confirmed cases Austria"
    }
   ]
  },
  {
   "title": "Todesfälle Weltweit",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 10 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_detail{country != \"Austria\"})  without (instance,job)",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Cov 19 Tests",
   "type": "graph",
   "gridPos": { "h": 6, "w": 12, "x": 0, "y": 14 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_tests) without (instance,job)",
     "legendFormat": "cov19 Tests"
    }
   ]
  }
 ]
}