{
 "title": "Covid-19-2",
 "time": { "from": "2020-02-29T23:00:00.000Z", "to": "now" },
 "refresh": "1h",
 "panels": [
  { "title": "Austria", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 0 } },
  {
   "title": "Fatality rate",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 1 },
   "targets": [
    {
     "expr": "sum(cov19_detail_dead) / sum(cov19_detail)"
    }
   ]
  },
  {
   "title": "Infected",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 5, "y": 1 },
   "targets": [
    { "expr": "cov19_confirmed - cov19_healed" }
   ]
  },
  {
   "title": "Tested",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 8, "y": 1 },
   "targets": [
    { "expr": "cov19_tests " }
   ]
  },
  {
   "title": "Infection Overview AUSTRIA by Bezirk",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 1 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_bezirk_infected", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Hospitalized",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 0, "y": 5 },
   "targets": [
    { "expr": "cov19_hospitalized" }
   ]
  },
  {
   "title": "in Intensive Care",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 4, "y": 5 },
   "targets": [
    { "expr": "cov19_intensive_care" }
   ]
  },
  {
   "title": "Healed",
   "type": "stat",
   "gridPos": { "h": 4, "w": 2, "x": 7, "y": 5 },
   "targets": [
    {
     "expr": "cov19_world_recovered{country=\"Austria\"}"
    }
   ]
  },
  {
   "title": "Deaths",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 5 },
   "targets": [
    { "expr": "sum(cov19_detail_dead)" }
   ]
  },
  {
   "title": "Stats overview (logarithmic)",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 9 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cov19_world_recovered{country=\"Austria\"}",
     "legendFormat": "Recovered"
    },
    { "expr": "cov19_confirmed", "legendFormat": "Infected" },
    { "expr": "cov19_hospitalized", "legendFormat": "Hospitalized" },
    { "expr": "cov19_intensive_care", "legendFormat": "Intensive Care" },
    { "expr": "sum(cov19_detail_dead)", "legendFormat": "Dead" }
   ]
  },
  {
   "title": "Age distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 17 },
   "format": "short",
   "valueName": "current",
   "targets": [
    { "expr": "cov19_age_distribution", "legendFormat": "{{group}} years" }
   ]
  },
  {
   "title": "Infection Overview AUSTRIA by Bezirk per 100k population",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 18 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_bezirk_infected_100k", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Sex distribution",
   "type": "grafana-piechart-panel",
   "gridPos": { "h": 9, "w": 12, "x": 0, "y": 26 },
   "format": "percent",
   "valueName": "current",
   "targets": [
    { "expr": "cov19_sex_distribution", "legendFormat": "{{sex}}" }
   ]
  },
  {
   "title": "Covid19 infections in Austria by Province (stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 35 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_detail{country=\"Austria\",province!=\", Salzburg\"}) without (instance,job,latitude,longitude,population)",
     "legendFormat": "{{province}}"
    }
   ]
  },
  {
   "title": "Infection Overview AUSTRIA",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 14, "w": 12, "x": 12, "y": 35 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_detail", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Covid19 deaths in Austria by Province (stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 45 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_detail_dead{country=\"Austria\",province!=\", Salzburg\"}) without (instance,job,latitude,longitude,population)",
     "legendFormat": "{{province}}"
    }
   ]
  },
  {
   "title": "Infection per 100k population in Austria",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 49 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_detail_infected_per_100k", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Covid19 infections in Austria by Bezirk (stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 55 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_bezirk_infected) without (instance,job,latitude,longitude,population)",
     "legendFormat": "{{bezirk}}"
    }
   ]
  },
  {
   "title": "Intensive Care Patients by Province",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 65 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cov19_intensive_care_detail", "legendFormat": "{{province}}" }
   ]
  },
  {
   "title": "Hospitalized in Austria",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 16, "w": 12, "x": 12, "y": 65 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_hospitalized_detail", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Hospitalized by Province",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 73 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cov19_hospitalized_detail", "legendFormat": "{{province}}" }
   ]
  },
  { "title": "Europe", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 81 } },
  {
   "title": "Covid19 Infections in Europe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 0, "y": 82 },
   "targets": [
    {
     "expr": "sum(cov19_world_infected{continent=\"Europe\"})"
    }
   ]
  },
  {
   "title": "Covid19 Deaths in Europe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 6, "x": 6, "y": 82 },
   "targets": [
    {
     "expr": "sum(cov19_world_death{continent=\"Europe\"})"
    }
   ]
  },
  {
   "title": "Covid19 fatality rate Europe",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 12, "y": 82 },
   "targets": [
    {
     "expr": " sum(cov19_world_death{continent=\"Europe\"}) / sum(cov19_world_infected{continent=\"Europe\"})"
    }
   ]
  },
  {
   "title": "Covid19 infections in Europe (stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_world_infected{continent=\"Europe\",country!=\"switzerland\", country!=\"United kingdom\"}) by(country) > 0 ",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Covid19 deaths in Europe (stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 86 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_world_death{continent=\"Europe\", country!=\"switzerland\", country!=\"United kingdom\"}) by(country) > 0 ",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Covid19 infections in Europe",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_world_infected{continent=\"Europe\",country!=\"switzerland\", country!=\"United kingdom\"}) by(country) > 0 ",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Covid19 deaths in Europe",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 96 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_world_death{continent=\"Europe\",country!=\"switzerland\", country!=\"United kingdom\"}) by(country) > 0 ",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Covid19 infections per 100k population Europe",
   "type": "graph",
   "gridPos": { "h": 11, "w": 12, "x": 0, "y": 106 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cov19_world_infected_per_100k{continent=\"Europe\",country!=\"switzerland\", country!=\"United kingdom\"}",
     "legendFormat": "{{country}}"
    }
   ]
  },
  { "title": "World", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 117 } },
  {
   "title": "Covid19 infections worldwide",
   "type": "stat",
   "gridPos": { "h": 4, "w": 5, "x": 0, "y": 118 },
   "targets": [
    { "expr": "sum(cov19_world_infected)" }
   ]
  },
  {
   "title": "Covid19 deaths worldwide",
   "type": "stat",
   "gridPos": { "h": 4, "w": 4, "x": 5, "y": 118 },
   "targets": [
    { "expr": "sum(cov19_world_death)" }
   ]
  },
  {
   "title": "Covid19 fatality rate World",
   "type": "stat",
   "gridPos": { "h": 4, "w": 3, "x": 9, "y": 118 },
   "targets": [
    {
     "expr": " sum(cov19_world_death) / sum(cov19_world_infected)"
    }
   ]
  },
  {
   "title": "Infection per 100k population World",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 118 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_world_infected_per_100k", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Covid19 infections worldwide (stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 122 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_world_infected) by(country) > 0 ",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Covid19 Recovered",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 132 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "cov19_world_recovered", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Covid19 deaths worldwide (stacked)",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 140 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_world_death) by(country) > 0 ",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Infection Overview WORLDWIDE",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 140 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_world_infected", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Infections by continent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 150 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cov19_world_infected{continent!=\"China\"}) by (continent)",
     "legendFormat": "{{continent}}"
    }
   ]
  },
  {
   "title": "Recovered Overview WORLDWIDE",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 150 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_world_recovered", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Deaths by continent",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 158 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cov19_world_death{continent!=\"China\"}) by (continent)",
     "legendFormat": "{{continent}}"
    }
   ]
  },
  {
   "title": "Fatality rate World",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 22, "w": 12, "x": 12, "y": 160 },
   "valueName": "current",
   "targets": [
    {
     "expr": "cov19_world_fatality_rate * 100",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "Covid19 fatality rate World",
   "type": "graph",
   "gridPos": { "h": 12, "w": 12, "x": 0, "y": 166 },
   "yaxes": [
    { "format": "percentunit" }
   ],
   "targets": [
    { "expr": "cov19_world_fatality_rate", "legendFormat": "{{country}}" }
   ]
  }
 ]
}