{
 "title": "Covid19-Wien",
 "time": { "from": "now-6h", "to": "now" },
 "panels": [
  {
   "title": "Infected in Wien",
   "type": "stat",
   "gridPos": { "h": 5, "w": 13, "x": 0, "y": 0 },
   "targets": [
    {
     "expr": "cov19_detail{province=\"Wien\"}"
    }
   ]
  },
  {
   "title": "Infection Overview AUSTRIA by Bezirk",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 0, "y": 5 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_bezirk_infected", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Infection Overview AUSTRIA by Bezirk per 100k population",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 17, "w": 12, "x": 12, "y": 5 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_bezirk_infected_100k", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Wien infected by Bezirk",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cov19_bezirk_infected{bezirk=~\".*Wien .*\"}",
     "legendFormat": "{{bezirk}}"
    }
   ]
  },
  {
   "title": "Wien infected by Bezirk per 100k population",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 22 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "cov19_bezirk_infected_100k{bezirk=~\".*Wien .*\"}",
     "legendFormat": "{{bezirk}}"
    }
   ]
  }
 ]
}