{
 "title": "COVID-19 GLOBAL OVERVIEW",
 "time": { "from": "now-7d", "to": "now" },
 "refresh": "1m",
 "panels": [
  {
   "title": "Info",
   "type": "text",
   "gridPos": { "h": 2, "w": 24, "x": 0, "y": 0 },
   "content": "### COVID-19 (CORONAVIRUS) GLOBAL OVERVIEW"
  },
  {
   "title": "Infection Overview AUSTRIA",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 2 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_detail", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "Infection Overview WORLDWIDE",
   "type": "grafana-worldmap-panel",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 2 },
   "valueName": "current",
   "targets": [
    { "expr": "cov19_world_infected", "legendFormat": "{{country}}" }
   ]
  },
  {
   "title": "COVID-19 Tests in AUSTRIA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 0, "y": 10 },
   "targets": [
    { "expr": "cov19_tests" }
   ]
  },
  {
   "title": "COVID-19 Infections in AUSTRIA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 5, "y": 10 },
   "targets": [
    { "expr": "cov19_confirmed" }
   ]
  },
  {
   "title": "COVID-19 Deaths in AUSTRIA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 10, "y": 10 },
   "targets": [
    {
     "expr": "sum(cov19_detail_dead{country=\"Austria\"})"
    }
   ]
  },
  {
   "title": "COVID-19 Healed Persons in AUSTRIA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 5, "x": 15, "y": 10 },
   "targets": [
    { "expr": "cov19_healed" }
   ]
  },
  {
   "title": "COVID-19 Fatality Ratio in AUSTRIA",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 10 },
   "targets": [
    {
     "expr": "100 / sum(cov19_world_infected{country=\"Austria\"}) * sum(cov19_detail_dead{country=\"Austria\"})"
    }
   ]
  },
  { "title": "ÖSTERREICH", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 15 } },
  {
   "title": "COVID-19 Infections in AUSTRIA by PROVINCE",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_detail) without(job, instance,latitude,longitude)",
     "legendFormat": "{{province}}"
    }
   ]
  },
  {
   "title": "COVID-19 Deaths in AUSTRIA by PROVINCE",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 16 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "max(cov19_detail_dead) without(instance,job,latitude,longitude)",
     "legendFormat": "{{province}}"
    }
   ]
  },
  { "title": "EUROPA", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 26 } },
  {
   "title": "COVID-19 Infections in EUROPE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 27 },
   "targets": [
    {
     "expr": "sum(cov19_world_infected{continent=\"Europe\"})"
    }
   ]
  },
  {
   "title": "COVID-19 Deaths in EUROPE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 27 },
   "targets": [
    {
     "expr": "sum(cov19_world_death{continent=\"Europe\"})"
    }
   ]
  },
  {
   "title": "COVID-19 Fatality Ratio in EUROPE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 27 },
   "targets": [
    {
     "expr": "100 / sum(cov19_world_infected{continent=\"Europe\"}) * sum(cov19_world_death{continent=\"Europe\"})"
    }
   ]
  },
  {
   "title": "COVID-19 Infections in EUROPE by COUNTRY",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cov19_world_infected{continent=\"Europe\"}) without(job,instance,longitude,latitude) > 0 ",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "COVID-19 Deaths in EUROPE by COUNTRY",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 32 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "cov19_world_death{continent=\"Europe\"} > 0",
     "legendFormat": "{{country}}"
    }
   ]
  },
  { "title": "WELTWEIT", "type": "row", "gridPos": { "h": 1, "w": 24, "x": 0, "y": 42 } },
  {
   "title": "COVID-19 Infections WORLDWIDE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 12, "x": 0, "y": 43 },
   "targets": [
    { "expr": "sum(cov19_world_infected)" }
   ]
  },
  {
   "title": "COVID-19 Deaths WORLDWIDE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 8, "x": 12, "y": 43 },
   "targets": [
    { "expr": "sum(cov19_world_death)" }
   ]
  },
  {
   "title": "COVID-19 Fatality Ratio WORLDWIDE",
   "type": "stat",
   "gridPos": { "h": 5, "w": 4, "x": 20, "y": 43 },
   "targets": [
    {
     "expr": "100 / sum(cov19_world_infected) * sum(cov19_world_death)"
    }
   ]
  },
  {
   "title": "COVID-19 Infections WORLDWIDE  by COUNTRY",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 0, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cov19_world_infected) without(instance,job,latitude,longitude) > 0",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "COVID-19 Deaths WORLDWIDE  by COUNTRY",
   "type": "graph",
   "gridPos": { "h": 10, "w": 12, "x": 12, "y": 48 },
   "yaxes": [
    { "format": "none" }
   ],
   "targets": [
    {
     "expr": "max(cov19_world_death) without(instance,job,latitude,longitude) > 0",
     "legendFormat": "{{country}}"
    }
   ]
  },
  {
   "title": "COVID-19 Infections by CONTINENT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 0, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cov19_world_infected{continent!=\"China\"}) by (continent)",
     "legendFormat": "{{continent}}"
    }
   ]
  },
  {
   "title": "COVID-19 Deaths by CONTINENT",
   "type": "graph",
   "gridPos": { "h": 8, "w": 12, "x": 12, "y": 58 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    {
     "expr": "sum(cov19_world_death{continent!=\"China\"}) by (continent)",
     "legendFormat": "{{continent}}"
    }
   ]
  },
  {
   "title": "Infection Overview WORLDWIDE",
   "type": "graph",
   "gridPos": { "h": 8, "w": 24, "x": 0, "y": 66 },
   "yaxes": [
    { "format": "short" }
   ],
   "targets": [
    { "expr": "sum(cov19_world_infected)", "legendFormat": "infected (prsons)" },
    { "expr": "sum(cov19_world_death)", "legendFormat": "deaths (persons)" },
    {
     "expr": "sum(cov19_world_infected) - sum(cov19_world_death)",
     "legendFormat": "recovery (Personen)"
    },
    {
     "expr": "100 / sum(cov19_world_infected) * sum(cov19_world_death)",
     "legendFormat": "fatality Ratio (%)"
    }
   ]
  }
 ]
}